default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("PGHOST", "/var/run/postgresql") %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("USER", nil)) %>

development:
  <<: *default
  database: github_quality_development

test:
  <<: *default
  database: github_quality_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>,
