default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: github_quality_development
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

test:
  <<: *default
  database: github_quality_test
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
